### ISSUE TITLE
How to invoke the modules inside ansible

### ISSUE THREAD

**Issue by ChennaiTechie** [IBM/ansible-for-i#11]
i have copied the modules folder to  /usr/share/ansible/plugins/modules & modules_utils to/usr/share/ansible/plugins/modules_utils and i get below error .. how do i load the modules so ansible can get it. 

[ansible@localhost ~]$ ansible-playbook -i hosts crtlib.yml

PLAY [ibmi] *********************************************************************************************************************************************************************************

TASK [run the CL command to create a library] ***********************************************************************************************************************************************
fatal: [1XX.16.XX0.70]: FAILED! => {"msg": "Could not find imported module support code for ibmi_cl_command.  Looked for either ibmi_util.py or ibmi.py"}
...ignoring

PLAY RECAP ***********************************************************************************************************

**Comment by LiJunBJZhu** [comment]
Can this issue be closed? I think it has been solved in https://github.com/IBM/cloud-i-blog/issues/2#event-3440507564.
