### ISSUE TITLE
Group PTF download failed with timeup

### ISSUE THREAD

**Issue by PraveenGovindarajan** [IBM/ansible-for-i#119]
I have used default values , after 15m its failed. 

fatal: [avfc400p.amerus.corp.tld]: FAILED! => {
    "changed": false,
    "command": "",
    "delta": "",
    "download_list": [],
    "invocation": {
        "module_args": {
            "become_user": null,
            "become_user_password": null,
            "check_PTF": "*NO",
            "delivery_format": "*SAVF",
            "image_directory": "*DFT",
            "joblog": false,
            "order": "*REQUIRED",
            "parameters": " ",
            "product": "*ONLYPRD",
            "ptf_id": "SF99433",
            "release": "*ONLYRLS",
            "reorder": "*YES",
            "time_out": "15m",
            "wait": true
        }
    },
    "job_info": "",
    "job_log": [
        {
            "FROM_INSTRUCTION": "*N",
            "FROM_LIBRARY": null,
            "FROM_MODULE": null,
            "FROM_PROCEDURE": null,
            "FROM_PROGRAM": "QWTSCSBJ",
            "FROM_USER": "E99875",
            "MESSAGE_FILE": null,
            "MESSAGE_ID": null,
            "MESSAGE_LIBRARY": null,
            "MESSAGE_SECOND_LEVEL_TEXT": null,
            "MESSAGE_SUBTYPE": null,
            "MESSAGE_TEXT": "SNDPTFORD PTFID((SF99433 *ONLYPRD *ONLYRLS)) DLVRYFMT(*SAVF) ORDER(*REQUIRED) REORDER(*YES) CHKPTF(*NO) IMGDIR(*DFT)",
            "MESSAGE_TIMESTAMP": "2022-01-03T07:04:03.348169",
            "MESSAGE_TYPE": "REQUEST",
            "ORDINAL_POSITION": 1,
            "SEVERITY": 0,
            "TO_INSTRUCTION": "*N",
            "TO_LIBRARY": null,
            "TO_MODULE": null,
            "TO_PROCEDURE": null,
            "TO_PROGRAM": "*EXT"
        }
    ],
    "msg": "Time up when waiting for SNDPTFORD complete.",
    "order_id": 0,
    "rc": 255,
    "stderr": "Failed to clear the job in joblog pending state.*** error  QWTRMVJL",
    "stderr_lines": [
        "Failed to clear the job in joblog pending state.*** error  QWTRMVJL"
    ],
    "stdout": "",
    "stdout_lines": []
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
avfc400p.amerus.corp.tld   : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by PraveenGovindarajan** [comment]
this is my code
---
- hosts: all
  gather_facts: false
  collections:
    -ibmi.power_ibmi
  tasks:
  - name: Download PTF group
    ibm.power_ibmi.ibmi_download_fix:
      ptf_id: "{{ ptf_group_number }}"
      delivery_format: "*SAVF"
      reorder: "*YES"
    register: download_fix_result

  - name: Print download information
    debug:
      var: download_fix_result

**Comment by pengzengyufish** [comment]
Hi, you can try to increase the time out value, since the  download time depends on the system and network condition.
For example:
name: Download PTF group
ibm.power_ibmi.ibmi_download_fix:
ptf_id: "{{ ptf_group_number }}"
delivery_format: "*SAVF"
reorder: "*YES"
time_out: "45m"
register: download_fix_result

**Comment by PraveenGovindarajan** [comment]
The problem is with SNDPTFORD command. Now works fine.
