### ISSUE TITLE
power_ibmi 1.6.0 bug in  sync_apply_ptf_group.yml

### ISSUE THREAD

**Issue by ghost** [IBM/ansible-for-i#125]
I recently changed from power_ibmi 1.5 to 1.6 to test remote imgclg installation.

But i encountered another thing.
I very often use the sync_apply_ptf_group.yml playbook to sync and install an iso ptfgroup.

With 1.6.0 of power_ibmi it fails with:

TASK [Include check_file role to check if files are the same] ******************************************************************************************************************************************************
Saturday 05 March 2022  10:50:34 +0100 (0:00:04.902)       0:00:28.065 ********
fatal: [server]: FAILED! => {"msg": "The conditional check 'stat_result.stat.exists is true' failed. The error was: template error while templating string: no test named 'true'. String: {% if stat_result.stat.exists is true %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/servsys/.ansible/collections/ansible_collections/ibm/power_ibmi/roles/sync_apply_ptf_group/tasks/main.yml': line 20, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Include check_file role to check if files are the same\n  ^ here\n"}

I switched back to 1.5.0 and the play book works flawlessly.
I hope you can fix that.

By the way: There is a small typo in the naming of the following task:
TASK [Get the PTF group information in download_status table, in case the order is still **dwonloading**]

Maybe they could fix that, too.

**Comment by pengzengyufish** [comment]
"dwonloading" will be fixed in next release.

Please try to upgrade ansible server to higher level. Seems your ansible doesn't support "is true".

Thank you

**Comment by ghost** [comment]
thanks, the update to python 3.8 and ansible 2.11.9 worked
