### ISSUE TITLE
fatal: [server]: FAILED! => {"msg": "Unable to import ibmi_cl_command due to invalid syntax"}

### ISSUE THREAD

**Issue by bricevollmer** [IBM/ansible-for-i#137]
Updated to collection v1.8 from v1.5.  - Now receiving invalid syntax errors when using collection modules

$ ansible-playbook playbook.yml
PLAY [all] ********************************************************************************************************************************************
TASK [text] *************************************************************************
fatal: [server]: FAILED! => {"msg": "Unable to import ibmi_cl_command due to invalid syntax"}
...ignoring

Rolling back to collection v1.5 allowed the playbook to run correctly again. Updated to 1.6 and this syntax error occurs. What changed with 1.6+ that I cannot import the modules?

**Comment by LiJunBJZhu** [comment]
What are the python versions on your control node and managed nodes?

**Comment by bricevollmer** [comment]
Ansible Engine is at v 2.9.27 using Python 2.7.5
IBMi nodes are using python 3.6.15

**Comment by LiJunBJZhu** [comment]
https://ibm.github.io/ansible-for-i/installation.html

In order to use this Ansible collection, you must have the Python v3.6+ installed on your Ansible server.
