### ISSUE TITLE
sync_apply_ptf_group_using_filedir.yml Playbook Problem

### ISSUE THREAD

**Issue by arthlingat** [IBM/ansible-for-i#139]
Hi,

There was an issue on sync_apply_ptf_group_using_filedir.yml playbook for 1.8.0, previously this was succesful on our end but now resulted to an error.

![image](https://user-images.githubusercontent.com/107974375/188346498-faef8a9c-c2cd-4814-9282-f619950fa3f1.png)

For your reference here are the sample variables we have inputted to check the concern.

ptf_group_dir: ptf/
repo_server: 172.69.11.96
target_system: 172.69.11.196

The image below indicates that we already tried to put the PTF file on the target system
![image](https://user-images.githubusercontent.com/107974375/188346547-77b95070-64ed-4c1e-b248-ab12801dc5aa.png)

**Comment by pengzengyufish** [comment]
Please try to upgrade to the latest Ansible version, should be 2.13 or higher.

**Comment by robgjertsen1** [comment]
I believe this is a problem with using an older Ansible version.
However, I have recently cleaned up the relevant code in this playbook and other areas, so that I don't believe this would occur now in version 2.0.1.
