### ISSUE TITLE
ibmi_fix - save_file_object parameter required?

### ISSUE THREAD

**Issue by ShibuyaHao** [IBM/ansible-for-i#155]
Hi, the documentation says save_file_object parameter is not required:
save_file_object
The object name of the save file to be installed.

required: false
type: str

But I get: "msg": "operation is load_only but all of the following are missing: save_file_object"} when I tried it without the parameter.

Is there a way to load and apply without specifying the save file?

**Comment by jpehrson** [comment]
@ShibuyaHao - The ibmi_fix module supports several different operations, which don't require the "save_file_object" parameter.  Hence, why it is not required.  For example, the apply_only, remove, and query operations do not require the "save_file_object" parameter.  However, the load_and_apply and load_only operations do require the "save_file_object" parameter.  So, it will depend on the operation parameter value you specify when calling the ibmi_fix module.

operation:
    description:
      - The operation for the fix, the options are as follows
      - load_and_apply will load the PTF and apply the PTF
      - apply_only will only apply the PTF
      - load_only will only load the PTF by LODPTF
      - remove will remove the PTF
      - query will return the specific PTF status
    choices: ['load_and_apply', 'apply_only', 'load_only', 'remove', 'query']
    type: str
    default: 'load_and_apply'

**Comment by ShibuyaHao** [comment]
OK thanks.
