### ISSUE TITLE
Creating a custom execution environment fails with: No packages matches 'python'

### ISSUE THREAD

**Issue by cunlifs** [IBM/ansible-for-i#163]
Hi when trying to build a new execution environment using ibm.power_ibmi with the following execution-environment & requirements files:
# cat execution-environment.yml 
---
version: 3

dependencies:
  galaxy: requirements.yml

options:
    package_manager_path: /usr/bin/microdnf

# cat requirements.yml 
---
collections:
  - name: ibm.power_ibmi
    source: https://galaxy.ansible.com

It fails with:
+ compile_packages='gcc
krb5-devel
libcurl-devel
libssh-devel
libxml2-devel
make
openssl-devel
python
python3-devel
python38-Cython
python38-devel
python39-devel'
+ '[' '!' -z 'gcc
krb5-devel
libcurl-devel
libssh-devel
libxml2-devel
make
openssl-devel
python
python3-devel
python38-Cython
python38-devel
python39-devel' ']'
+ /usr/bin/microdnf install -y --nodocs --setopt install_weak_deps=0 gcc krb5-devel libcurl-devel libssh-devel libxml2-devel make openssl-devel python python3-devel python38-Cython python38-devel python39-devel
Downloading metadata...
Downloading metadata...
Downloading metadata...
Downloading metadata...
Downloading metadata...
error: No package matches 'python'
Error: building at STEP "RUN /output/scripts/assemble": while running runtime: exit status 1

Should this really be 'python'? The same build works with ibm.power_aix, vios collections etc.

**Comment by syahrul-aiman** [comment]
Hi @cunlifs 

Not sure if this will help. But here's my execution environment and it works for me so far:
https://github.com/syahrul-aiman/ibm_power

And here's the image at quay.io:
https://quay.io/repository/syahrul_aiman_my/ibm_power

both are public.

**Comment by laenglea** [comment]
Hi,
just wanna say same issue here...

microdnf wants to install python 

`error: No package matches 'python'`

**Comment by robgjertsen1** [comment]
OK, thanks. I will correct bindep.txt.

**Comment by laenglea** [comment]
Hi @robgjertsen1,
any progress here?

Regards,
Alex

**Comment by robgjertsen1** [comment]
I've included this update in the internal code base, so it will be in the next collection update (and will push the changes to github then).

**Comment by robgjertsen1** [comment]
Fixed with release 2.0.1.
