### ISSUE TITLE
ibmi_cl_command return value job_name empty

### ISSUE THREAD

**Issue by ShibuyaHao** [IBM/ansible-for-i#190]
Hi,
I get empty return value on "job_name": "" when I run my task below. Anyone know why?

  tasks:
  - name: test 
    ibm.power_ibmi.ibmi_cl_command: 
      cmd: 'DSPMSG MSGQ(QSYSOPR)'
    register: job

Output:
 {"changed": false, "cmd": "DSPMSG MSGQ(QSYSOPR)", "delta": "0:00:00.448407", "end": "2024-03-18 15:42:01.670194", "job_log": [], "job_name": "", "joblog": false, "rc": 0, "start": "2024-03-18 15:42:01.221787", "stderr": "", "stderr_lines": [], "stdout": "CPC9802: Printer output created

Best Regards
Sihao

**Comment by robgjertsen1** [comment]
For display commands or commands using OUTPUT parameter, the command is run with the system command versus iToolKit and doesn't provide job_log and job_name information.
With joblog parameter toggled on, other types of commands will return the job information.

Please see https://ibm.github.io/ansible-for-i/modules/ibmi_cl_command.html
