### ISSUE TITLE
ibmi_facts module error RC 999 Exception occurred: 'SYSNAME'

### ISSUE THREAD

**Issue by Pierroto69** [IBM/ansible-for-i#192]
Hi , I have an error running module ibmi_facts , see below the playbook and error log  :
we are running on ansible core 2.15.4 and node ibm i partition : V7R3M0 with python3  version 3.6.15-1   
Thanks a lot for your support

**Playbook:**
---
- name: IBM i download a list of individual PTFs
  hosts: all
  gather_facts: true
  
  tasks:
    - name: Return ibmi_facts
      ibm.power_ibmi.ibmi_facts:

**error log** :
The full traceback is:
  File "/tmp/ansible_ibm.power_ibmi.ibmi_facts_payload_ukrj1o4x/ansible_ibm.power_ibmi.ibmi_facts_payload.zip/ansible_collections/ibm/power_ibmi/plugins/modules/ibmi_facts.py", line 391, in run_module
fatal: [iis_testpartition]: FAILED! => {
    "ansible_facts": {},
    "changed": false,
    "invocation": {
        "module_args": {
            "filter": "*"
        }
    },
    "msg": "Exception occurred: 'SYSNAME'",
    "rc": 999

**Comment by robgjertsen1** [comment]
I have seen problems at times with using ansible and python versions that aren't compatible (typically one is older version and other is much newer). If you are running ansible core 2.15 on the control node, then I would try using python 3.9 on there also instead of python 3.6. It should be OK to run python 3.6 on the target nodes (target level of python is typically a wider range of versions).

**Comment by Pierroto69** [comment]
Hi Rob, thanks for your support but I run again with python version 3.9.18 on target node but same error

**Comment by robgjertsen1** [comment]
I am not clear on python version being used on control node. You mention 2.15 ansible-core and target node python 3.6 on the IBM i originally. You've now tried running with python 3.9 on target node What python version is being used on the control node (output from "ansible --version" on control node will provide this info)? 
With ansible-core 2.15 you want to be at python 3.9 or higher on control node. An exception like this generally indicates some environmental issue. I tried this is in my environment with ansible 2.15 and 3.9 on my control node and either python 3.6 or 3.9 on IBM i target node and it is looking OK (running V7R4 on IBM i in this instance).

**Comment by Pierroto69** [comment]
Hi Rob yesterday the target node ibm i has been upgraded from V7R3 to V7R4 and it's works fine now

**Comment by Pierroto69** [comment]
the target node ibm i has been upgraded from V7R3 to V7R4 and it's works fine now

**Comment by robgjertsen1** [comment]
OK, good. Not sure why you were having a problem with V7R3, but glad it works now on V7R4.
