### ISSUE TITLE
Problem of timeout to PSP

### ISSUE THREAD

**Issue by JaKo8103** [IBM/ansible-for-i#194]
I used check_download_ptf_group.yml
Now in 90% I have a problem of:

"fix_group_check_result": {
        "changed": false,
        "count": 1,
        "elapsed_time": "0:00:10.165574",
        "end": "2024-04-16 12:31:36.604073",
        "failed": false,
        "group_info": [
            {
                "error": "The read operation timed out",
                "url": "https://www.ibm.com/support/pages/ibm-i-group-ptfs-level"
            }
        ],
        "http_agent": "ansible/ibm.power_ibmi",
        "rc": 0,
        "start": "2024-04-16 12:31:26.438499",
        "stderr": "",
        "stderr_lines": [],
        "timeout": 10,
        "validate_certs": true
		
I see in role we used 
- name: Check and get the latest PTF group information on PSP
  ibm.power_ibmi.ibmi_fix_group_check:
    groups: '{{ ptf_group }}'
  register: fix_group_check_result
  
In ibmi_fix_group_check.py is option timeout

  timeout:
    description:
      - Timeout in seconds for URL request.
    type: int
    default: 10
    required: false

Where and how to add in check_download_ptf_group.yml more timeout to check site whit PSP ?

**Comment by robgjertsen1** [comment]
Yes, I've noticed that it is taking longer at least in the past week with fix check, so 10 seconds is insufficient a lot of the time.
Ideally we would figure out why the web server is taking longer and that would be fixed, but I may need to bump up the default for now to get around this in the 2 fix check modules.
Longer term it would probably be nice to have the roles that call ibmi_fix_check and ibmi_fix_group_check modules be
able to specify a timeout (optional parameter).

In regard to your playbook, you can certainly specify a different timeout parameter for the fix check module doing something like the following:

    - name: Task query_a_single_group
      ibm.power_ibmi.ibmi_fix_group_check:
        groups:
          - "SF99713"
        timeout: 30

**Comment by JaKo8103** [comment]
Rob
I use GALAXY so I can't change it manually.
You can change these two modules (timeout=60) in gjertsen-patch-fix-check

**Comment by JaKo8103** [comment]
Add info:
ibmi_fix_group_check have a old site:
  "error": "HTTP Error 404: Not Found",
                    "url": "https://www.ibm.com/support/pages/uid/nas4SF99713"
I work in galaxy that I not have permission to change a script python.

**Comment by robgjertsen1** [comment]
Yes, I may do a minor update to include the fix for recent PSP breakage and then add in longer default timeout to those modules. I have noticed this week that it is failing at least 50% of the time with 10 second timeout, which I hadn't seen before. Possible this is related to recent PSP web page updates.

**Comment by JaKo8103** [comment]
When can we expect your correction?

**Comment by robgjertsen1** [comment]
I will try to get an update out next week.

**Comment by Pierroto69** [comment]
Hi , we have the same problem and waiting also the correction , thks Rob for your support

**Comment by robgjertsen1** [comment]
Fixed with 2.0.2. I have changed the timeout to a 60 second default.

**Comment by Pierroto69** [comment]
Hi Rob , thanks it's works fine :)
