### ISSUE TITLE
QUESTION : How to apply ptf or group ptf to the REPO SERVER itself 

### ISSUE THREAD

**Issue by Pierroto69** [IBM/ansible-for-i#203]
Hi team, How to apply ptf or group ptf to the REPO SERVER himself 
we use the playbook to load/apply on different targets node from the repo server it's works fine BUT when we want to run it on REPO Server himself , I mean apply ptf or group ptf to the REPO Server it dosen't work as transfert savf (ptf) or bin (group ptf) failed 

What is your recommendation ? is there a specific playbook which extract info from report and install ptf to the repo himself ?

Many Thanks

**Comment by robgjertsen1** [comment]
It would be helpful to have more specifics such as seeing the playbook and the roles and modules it is invoking, along with the output that includes the error with using the repo server as the target. Not sure off the top of my head why this would not work, but it could be a current limitation.

**Comment by Pierroto69** [comment]
Hi Rob, we test the playbook "fix_repo_download_apply_individual_ptfs" with repo server = target node and it's works except the fact that the SAVF and cover letter has been deleted at the end of load / apply . The problem is that the catalog is updated with the right ptf and information savf location , that mean for next time we will run the playbook it will not work as the ptf is in catalog but  the savf not exist
What do you suggest for solution ? thanks

**Comment by robgjertsen1** [comment]
The lower level call to role "sync_apply_individual_ptfs" that would occur with this playbook is probably using default delete as true, so I am wondering if this is cleaning up the downloaded install image on the repo server when you don't want it to. Typically you want the image cleaned up afterwards on the target nodes because normally it has been copied / sync'ed and no longer needed after load / apply.
You could check if breaking this up with separate use of "check_download_individual_ptfs.yml" to download and then call to "sync_apply_individual_ptfs.yml" with delete as false for the repo server resolves this.

**Comment by Pierroto69** [comment]
HI Rob, we well understand,  but we cannot change roles/modules as we execute playbook on shared tower ansible very secure . So  is it possible to increase the level of the parameter variable "sync_apply_individual_ptfs_delete" of role "sync_apply_individual_ptfs" to the role  "fix_repo_download_apply_individual_ptfs" with same variable entry (default "true") , 
Could be in a next release ?
Thanks a lot

**Comment by robgjertsen1** [comment]
Sure, my suggestion was to use 2 different playbooks from fix management use case to do the same thing (with control over "delete" option with copied images) as the one playbook from use case that you are using and verify that it works on the repo server. This would just be a workaround to see if that resolves the issue and doesn't involve changing modules or roles.
I would have to see whether this could be included in the next release.

**Comment by robgjertsen1** [comment]
Surfacing delete option with 3.2.0.
