### ISSUE TITLE
ibmi_synchronize_files.py cannot find ibmi_sync_files.py

### ISSUE THREAD

**Issue by MexCFood** [IBM/ansible-for-i#205]
With the change to absolute pathing and the removal of collections: ibm.power_ibmi, a call to ibmi_synchronize_files fails with message "The module ibmi_sync_files was not found in configured module paths"

Absolute pathing should either be added into "ansible-for-i-devel\plugins\action\ibmi_synchronize_files.py" line 83, or collections: ibm.power_ibmi should be added back into certain playbooks (such as ansible-for-i-devel\usecases\fix_management\sync_apply_individual_ptfs_lv1.yml.)

Thanks!

**Comment by robgjertsen1** [comment]
OK, thanks for letting me know. I haven't seen this in my testing such as with the use case playbook sync_apply_individual_ptfs_lv1.yml, which I tested a couple of months ago.

We are now required to use the fully qualified collection names (FQCN) with modules in Ansible to retain certification with Redhat (to pass with the code checking tool). I believe the checking tool also complained about the use of the collections keyword which was why "collections:" was removed. Leaving the only option as updating plugin python files to use the fully qualified name if we need to adjust this.
Interesting that this would break things from using "collections:" with unqualified name to using fully qualified name without collections keyword. 

Just wondering if there is an environmental difference. Do you have the following in your ansible config file?

library=~/.ansible/collections/ansible_collections/ibm/power_ibmi/plugins/modules
action_plugins=~/.ansible/collections/ansible_collections/ibm/power_ibmi/plugins/action

**Comment by MexCFood** [comment]
Hey Rob, my pleasure - thanks for looking into it.  That makes sense as to
why it was removed.

We are using the automation platform, with an ibmi specific execution
environment built through ansible-builder.  I do not see that line in my
Ansible cfg file.  With that in mind, I am looking into where it gets the path in an EE at all 😃

**Comment by MexCFood** [comment]
Okay - so our ee is just looking in the default location
/usr/share/Ansible/collections/ansible_collections.  we do not have any
other specific environment variables pointing to this module,
so I assume we rely on the FQN (or the collections call) to find where in
the path to look (/ibm/power_ibmi/plugins/modules/ibmi_sync.py).

**Comment by robgjertsen1** [comment]
Seeing if you were able to resolve this issue.

**Comment by MexCFood** [comment]
Hey Rob - thanks for following up.  I was able to circumvent it by adding
the collections statement to a custom version of
sync_apply_individual_ptfs_lv1.yml so this is not causing me a problem at
this time.  I do expect it would still be an issue otherwise, as the
plugins/action/ibmi_synchronize_files.py file is referencing the module
'ibmi_sync_files' without FQCN.

**Comment by robgjertsen1** [comment]
Added in FQCN for collection module references with plugins for release 3.2.0.
