### ISSUE TITLE
Logical problem with the role fix_repo_download_apply_individual_ptfs

### ISSUE THREAD

**Issue by yassinehamzaoui** [IBM/ansible-for-i#209]
Hello team,

When we include the role : ibm.power_ibmi.fix_repo_download_apply_individual_ptfs in our existing playbook, at the end of the execution there's a meta : end_host which causes a problem of terminating our next tasks, there's some bypass methods but i was wondering why you have added the meta: end_host in that particular playbook, btw we use another roles and we didn't face that problem, is it something mandatory ? or it is a missing piece of code there left ?

Thanks.

**Comment by robgjertsen1** [comment]
On first examination, I'm not entirely clear why there is a "meta: end_host" at the end of that last block for the role fix_repo_download_apply_individual_ptfs. The meta task has been in the role for quite some time. I will look closer, but
seems like something that doesn't belong there.
This construct is typically used with a fatal error for a target host. There are a number of playbooks in the fix management use case that use meta: end_host for an unrecoverable error.

**Comment by yassinehamzaoui** [comment]
Hi @robgjertsen1, the problem is that even with a successful execution from what we have tested still having the end_host, it is not linked to any fatal error condition .. so i was wondering if is it possible to remove that task of end_host.

**Comment by robgjertsen1** [comment]
It doesn't make sense to have it there from what I can tell, so I am expecting to remove that meta task.

**Comment by yassinehamzaoui** [comment]
i have created a PR for that https://github.com/IBM/ansible-for-i/pull/210

**Comment by robgjertsen1** [comment]
OK, thanks. Yes, I will correct this for the next update.

**Comment by robgjertsen1** [comment]
Resolved with 3.2.0.
