### ISSUE TITLE
ibm_fix_group_check - Empty Data from get_ptf_list_from_web

### ISSUE THREAD

**Issue by cmh716** [IBM/ansible-for-i#212]
The ptf_list array returned from this appears to be empty.  It seems the issue may have started early 2024.  I suspect it's because these nasXXXXX URLS now redirect to location.

**Comment by robgjertsen1** [comment]
Hello, I am using issue 204 to track the problem with PTF groups. I should have an update in the next release that
addresses this issue with group ptfs (latest info and including PTF info). Unfortunately the PSP changes started causing problem mid-year. I will close this as a duplicate.
