### ISSUE TITLE
Certified Ansible Collections

### ISSUE THREAD

**Issue by nicholas-chia** [IBM/ansible-for-i#34]
Are you considering moving this in Certified Ansible Collections soon?

**Comment by changlexc** [comment]
Do you mean this?  
https://galaxy.ansible.com/ibm/power_ibmi

**Comment by nicholas-chia** [comment]
https://access.redhat.com/articles/3642632

Yes, it is currently listed as a community supported Ansible Collection.

Becoming certified status gets this collection into Ansible Automation Hub. That means it will be supported by IBM and Red Hat as well. Any roadmap for that to happen?

**Comment by changlexc** [comment]
assign to li jun and wang yun to answer this.

**Comment by LiJunBJZhu** [comment]
Hi Nicolas, this collection will go to Automation Hub very soon.

**Comment by LiJunBJZhu** [comment]
@nicholas-chia, it is ready. See announcement here https://www.ansible.com/integrations/infrastructure/ibm-power-systems
and try-it here https://www.redhat.com/en/technologies/management/ansible/try-it
