### ISSUE TITLE
Playbook enable_ibmi_offline fails when executimg yum install

### ISSUE THREAD

**Issue by robinsg** [IBM/ansible-for-i#35]
**Playbook:**

ibmi_install_python.yml fails on the following task:

    - name: install the package
      raw: "/QOpensys/pkgs/bin/yum install {{remote_temp_dir}}/*.rpm -y"
      when: has_rpm_to_be_installed

Even though yum has been installed using the bootstrap files it still attempts to access the IBM site public.dhe.ibm.com:

TASK [install the package] *******************************************************************************************************************************************************************************************************************
fatal: [serverXYZ]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 1, "stderr": "Shared connection to 10.xx.yy.zz closed.\r\n", "stderr_lines": ["Shared connection to 10.xx.yy.zz closed."], "stdout": "https://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo/repodata/repomd.xml: [Errno 14] curl#6 - \"Could not resolve host: public.dhe.ibm.com\"\r\nTrying other mirror.\r\nError: Cannot retrieve repository metadata (repomd.xml) for repository: ibm. Please verify its path and try again\r\n", "stdout_lines": ["https://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo/repodata/repomd.xml: [Errno 14] curl#6 - \"Could not resolve host: public.dhe.ibm.com\"", "Trying other mirror.", "Error: Cannot retrieve repository metadata (repomd.xml) for repository: ibm. Please verify its path and try again"]}

**Cause:**

File /QOpenSys/etc/yum/repos.d/ibm.repo has the public website enabled:

[ibm]
name=ibm
baseurl=https://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo
enabled=1
gpgcheck=0

**Workaround:**

Edit /QOpenSys/etc/yum/repos.d/ibm.repo to change the enabled parameter to 0

[ibm]
name=ibm
baseurl=https://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo
**enabled=0**
gpgcheck=0

**Potential fix**

Immediately after the bootstrap installation has completed run a task to amend /QOpenSys/etc/yum/repos.d/ibm.rep to disable the repo by setting enabled=0

**Comment by LiJunBJZhu** [comment]
Normally the error "Could not resolve host: public.dhe.ibm.com" means the DNS of the IBM i is set up properly. Could you please login your IBM i, run "cfgtcp -> option 12" to check whether the DNS has been configured? Thanks.

                        Change TCP/IP Domain (CHGTCPDMN)              
                                                                      
 Type choices, press Enter.                                           
                                                                      
 Domain name server:                                                  
   Internet address . . . . . . .   *SAME                             
                                                                      
   Internet address . . . . . . .   *SAME                             
                                                                      
   Internet address . . . . . . .   *SAME

**Comment by robinsg** [comment]
I think you’ve misunderstood.

The LPAR has no access to the internet so yum should not be attempting to use the IBM repository.

Even if DNS was set up correctly the firewall and proxy servers would block the yum request.

The point of this playbook is to install yum and python without the LPAR having access to the internet.

**Comment by LiJunBJZhu** [comment]
Oh, yes, good catch. I didn't realize that it is for offline IBM i enablement. We will make the change to set the enabled=0 soon.

**Comment by ThePrez** [comment]
Rather than `enabled=0`, you could use `skip_if_unavailable=1`. That way, the public repo can still be used if needed, but a lack of connection will be non-fatal.

**Comment by robinsg** [comment]
Great idea but the whole point of this playbook is that the LPAR hasn't got that connectivity to the internet.

Saying that, I do prefer this to hard coding enabled=0 in case the LPAR does eventually get access, possibly via a proxy server. At least the repo file would be set correctly in readiness.

**Comment by LiJunBJZhu** [comment]
Fixed in power_ibmi v1.0.1, enabled is set to 0.
