### ISSUE TITLE
ibmi_reboot doesn't seem to work correctly

### ISSUE THREAD

**Issue by jared-draper** [IBM/ansible-for-i#58]
the ibmi_reboot module doesn't seem to work correctly.  It just returns the following:

{
    "reboot": false,
    "msg": "'ansible_facts'",
    "_ansible_no_log": false,
    "changed": false
}

Also I think the documentation for the module might be incorrect?  It references just reboot:  shouldn't it be ibmi_reboot: 

EXAMPLES = r'''
- name: Unconditionally reboot the machine with all defaults
  reboot:  <--- 

- name: Reboot a slow machine that might have lots of updates to apply
  reboot: <----
    reeboot_timeout: 3600
'''

**Comment by changlexc** [comment]
yes document issue, already fixed in dev branch, will have a fix pack soon
