### ISSUE TITLE
Error when using ibmi_fix_group_check module

### ISSUE THREAD

**Issue by robinsg** [IBM/ansible-for-i#73]
I'm using version 1.2.1 of the ibm.power_ibmi collection.

I get a urlopen error when I run the following:

```
ansible myserver -m ibm.power_ibmi.ibmi_fix_group_check -a "groups=SF99728"  -vvv
myserver | SUCCESS => {
    "changed": false,
    "count": 1,
    "elapsed_time": "0:00:02.270273",
    "end": "2021-02-04 15:59:53.869843",
    "group_info": [
        {
            "error": "<urlopen error [Errno 8] Hostname and service name not provided or found>",
            "url": "https://www.ibm.com/support/pages/node/6211843"
        }
    ],
    "invocation": {
        "module_args": {
            "groups": [
                "SF99728"
            ],
            "timeout": 10,
            "validate_certs": true
        }
    },
    "rc": 0,
    "start": "2021-02-04 15:59:51.599570",
    "stderr": "",
    "stderr_lines": []
}
```

I'm assuming that the IBM i server I'm using requires internet access to https://www.ibm.com.

1. Can you confirm that is the case?
2. The LPAR already has proxy access to https://public.ibm.com and https://esupport.ibm.com. Are there any other access requirements for the LPAR to use the fix management modules succcessfully?

**Comment by changlexc** [comment]
You can set input validate_certs as false to have a try.

**Comment by robinsg** [comment]
Where do i specify this?

**Comment by robinsg** [comment]
Hello,

I tried:

ansible myserver -m ibm.power_ibmi.ibmi_fix_group_check -a "groups=SF99728"  -e "validate_certs=false"

The error message is the same as before.

Please advise how I can workaround this issue.

**Comment by changlexc** [comment]
Can you try 'curl https://www.ibm.com/support/pages/node/6211843' in your control node, looks like the error is not related to the cert, most likely the control node has network access problem.

**Comment by robinsg** [comment]
I'll need to get a proxy server rule in place but that makes sense.

**Comment by robinsg** [comment]
This issue was fixed by adding a proxy_http enviroment variable to the beginning of the playbook e.g.

  environment:
        http_proxy: http://my.proxy_server.name:11000
        https_proxy: http://my.proxy_server.name:11000
