### ISSUE TITLE
Ansible Controller on IBM i | Ansible.cfg

### ISSUE THREAD

**Issue by mad5bo** [IBM/ansible-for-i#75]
Hello,
I have two concerns.

Creating an ansible.cfg file on path /home/QSECOFR/.ansible/collections/ansible_collections/ibm/power_ibmi/playbooks/
**ls**
ansible.cfg                        

**vi ansible.cfg**
[defaults]
roles_path = ../roles
inventory       = hosts_ibmi.ini

[ssh_connection]
pipelining = True

**_What would be the preferred parameters to be use on ansible.cfg for Ansible ctrl for IBM i?_**

By the other side, issuing ansible --version
**# ansible --version**
ansible 2.9.9
  **config file = None**
  configured module search path = ['/HOME/QSECOFR/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /QOpenSys/pkgs/lib/python3.6/site-packages/ansible
  executable location = ./ansible
  python version = 3.6.12 (default, Nov 10 2020, 13:50:57) [GCC 6.3.0]

config file is none **How should I attach the ansible.cfg created before to Ansible?**

Regards
MAD

**Comment by LiJunBJZhu** [comment]
When you created an ansible.cfg file in /etc/ansible with below data:
 
$ cat /etc/ansible/ansible.cfg
[defaults]
library=~/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
action_plugins=~/.ansible/collections/ansible_collections/ibm/power_ibmi/plugins/action
 
You will get a correct ansible --version output like --
 
$ ansible --version
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  ......
 
You can also create the inventory file there --
 
$ cat /etc/ansible/hosts 
[local]
localhost ansible_connection=local
[ibmi]
ut28p60 ansible_ssh_user=xumeng  ansible_python_interpreter=/QOpenSys/pkgs/bin/python2

**Comment by mad5bo** [comment]
Hi, thanks by the input
What about the parameter inventory at for ansible.cfg,  Of course, inventory will depends on where the inventory file is, although you can use multiple inventory files, is it correct as follows? considering that host_ibmi.ini comes by default in Ansible Galaxy colletions
![image](https://user-images.githubusercontent.com/68882369/108866715-37d22400-75d3-11eb-945f-194a72a0972d.png)

**Comment by mad5bo** [comment]
Thanks!
