### ISSUE TITLE
HTTP error 403 Forbidden

### ISSUE THREAD

**Issue by Ludovic-Menard** [IBM/ansible-for-i#77]
Hello,
I am trying to check PTF using ibmi_fix_group_check module.  I tried validate_certs: False or True.
This is the test
tasks:
    - name: query_a_group_and_a_cum
      ibmi_fix_group_check:
        groups:
          - "SF99740"
        validate_certs: False

I received a HTTP error 403. My managed node has an access to internet.
        "group_info": [
            {
                "error": "HTTP Error 403: Forbidden",
                "url": "https://www.ibm.com/support/pages/node/6211843"

Thanks for you help.
Ludo

**Comment by changlexc** [comment]
Can you try 'curl https://www.ibm.com/support/pages/node/6211843' in your control node to test the connecting? This module  calls this curl command underneath.

**Comment by Ludovic-Menard** [comment]
Hello, 
Thanks for your answer but when I use this command on my control node, I have the same result (403 forbidden).
I uploaded the result in result.txt file
[result.txt](https://github.com/IBM/ansible-for-i/files/6014358/result.txt)

Thanks
Ludo

**Comment by changlexc** [comment]
I think a quick answer from my point is that you would need to ask for your network admin for help to see why the url can not be accessed. I don't think this Ansible module can have any workaround to make it work.

**Comment by robgjertsen1** [comment]
The fix for this will be in 1.92. For now there is a patch branch for the issue: https://github.com/IBM/ansible-for-i/tree/gjertsen-patch-fix-check

This is same problem as recent issue #152: https://github.com/IBM/ansible-for-i/issues/152
