### ISSUE TITLE
doc: "Edit on GitHub" link is broken

### ISSUE THREAD

**Issue by ThePrez** [IBM/ansible-for-i#80]
On this page and others: https://ibm.github.io/ansible-for-i/index.html
The "Edit on GitHub" link (upper right) is broken. In this specific case, it links to https://github.com/IBM/ansible_for_i/blob/devel/docs/source/index.rst
It should instead link to https://github.com/IBM/ansible-for-i/blob/devel/docs/source/index.rst
(note the `-` vs `_`)

**Comment by LiJunBJZhu** [comment]
Fixed.
