### ISSUE TITLE
No inventory was parsed, only implicit localhost is available

### ISSUE THREAD

**Issue by mad5bo** [IBM/ansible-for-i#81]
hi,
Trying to issue the following command, the next message is displayed
![image](https://user-images.githubusercontent.com/68882369/109105305-6b649980-770c-11eb-8404-d2345b0af931.png)
However, changing the directory and path where  the ansible.cfg and hosts_ibmi.ini resides, the  issued commands run succesfully
![image](https://user-images.githubusercontent.com/68882369/109105483-c8f8e600-770c-11eb-8538-7e6bb4174c06.png)
Is there a manner to run ansible commands from outside the directory where ansible.cfg and hosts file resides? This is a case with Ansible controller installed and configured on IBM i.

**Comment by LiJunBJZhu** [comment]
Run "ansible -m ping all -i <your_intentory_path>" instead.

**Comment by mad5bo** [comment]
Thanks!
