### ISSUE TITLE
 [openstack]: FAILED! => {"changed": false, "msg": "openstacksdk is required for this module"}

### ISSUE THREAD

**Issue by mad5bo** [IBM/ansible-for-i#86]
hi, 

The question regarding the message  "openstacksdk is required for this module" is because trying to use the roles such as: deploy_vm_via_powervc, display_network_info_via_powervc, all related to powervc. So Does the requirements to use those roles is to have installed _ansible-galaxy collection install openstack.cloud_, and  _openstacksdk_ on control node? or it can be used without that it is not clear at README of each role. Can you please confirm that?

**Comment by LiJunBJZhu** [comment]
Openstacksdk is required be installed o powervc server. It is one required dependencies of openstack modules. You can install "pip install openstacksdk" or "pip3 install openstacksdk" on powervc server.

**Comment by mad5bo** [comment]
Thanks!
