### ISSUE TITLE
ibmi-fix-group-compare.yml

### ISSUE THREAD

**Issue by Ludovic-Menard** [IBM/ansible-for-i#92]
Hello,
When I want to the playbook ibmi-fix-group-compare.yml, the role check_ptf_groups doesn't exist. 
I checked on roles directory and I don't find this role. 
What is the right role for this playbook ? check_ptf, check_ptf_groups_against_fix_repo

Thanks
Ludo

**Comment by LiJunBJZhu** [comment]
Hi,

Actually ibmi-fix-group-compare.yml is an out-of-date playbook which should be removed.  We will fix that soon.

Please use ibmi_fix_group_compare.yml instead.

**Comment by Ludovic-Menard** [comment]
Thanks. I will use it
