### ISSUE TITLE
Integration Terraform with Ansible

### ISSUE THREAD

**Issue by mad5bo** [IBM/ansible-for-i#97]
Hi, 

Does Terraform provisioner "remote-exec" is compatible against Ansible controller on IBM i? I am trying an integration against Terraform with IBM i control node.
```
provisioner "remote-exec" {
    command = ["sleep 60; ansible-playbook -u qciuser --private-key ${var.ssh_keyname} -i ${openstack_compute_instance_v2.PowerVC-VM.*.network.0.fixed_ip_v4} ibmi-install-nodejs.yml"]
  }
```

**Comment by LiJunBJZhu** [comment]
I don't see there are any blockers. Please try it.

**Comment by robgjertsen1** [comment]
Closing this out due to inactivity (and not an obvious reason it shouldn't work).
